baseURL = "https://webwriterscollective.com/"
locale = "en-GB"
title = "Web Writers’ Collective"
theme = "webwriterscollective"

[taxonomies]
  tag = "tags"
  author = "authors"

[markup.tableOfContents]
  startLevel = 1
  endLevel = 1

[markup]
[markup.goldmark]
  [markup.goldmark.parser]
    autoHeadingID = true
  [markup.goldmark.renderer]
    unsafe = true

[mediaTypes."application/vnd.webwriterscollective.combined-rss"]
  suffixes = [""]
  delimiter = ""

[mediaTypes."application/vnd.webwriterscollective.noticeboard-rss"]
  suffixes = [""]
  delimiter = ""

[mediaTypes."application/vnd.webwriterscollective.anthology-rss"]
  suffixes = [""]
  delimiter = ""

[outputFormats.CombinedRSS]
  mediaType = "application/vnd.webwriterscollective.combined-rss"
  baseName = "feed"
  isPlainText = true
  rel = "alternate"

[outputFormats.NoticeboardRSS]
  mediaType = "application/vnd.webwriterscollective.noticeboard-rss"
  baseName = "feed"
  isPlainText = true
  rel = "alternate"

[outputFormats.AnthologyArticlesRSS]
  mediaType = "application/vnd.webwriterscollective.anthology-rss"
  baseName = "feed"
  isPlainText = true
  rel = "alternate"

[outputs]
  home = ["HTML", "CombinedRSS"]
