baseURL = "https://webwriterscollective.com/"
locale = "en-GB"
title = "Web Writers’ Collective"
theme = "webwriterscollective"

[taxonomies]
  tag = "tags"
  author = "authors"

[markup.tableOfContents]
  startLevel = 1
  endLevel = 1

[markup]
[markup.goldmark]
  [markup.goldmark.parser]
    autoHeadingID = true
  [markup.goldmark.renderer]
    unsafe = true

[outputFormats.CombinedRSS]
  mediaType = "application/rss+xml"
  baseName = "feed"
  isPlainText = true
  rel = "alternate"

[outputFormats.NoticeboardRSS]
  mediaType = "application/rss+xml"
  baseName = "feed"
  isPlainText = true
  rel = "alternate"

[outputFormats.AnthologyArticlesRSS]
  mediaType = "application/rss+xml"
  baseName = "feed"
  isPlainText = true
  rel = "alternate"

[outputs]
  home = ["HTML", "CombinedRSS"]
